### ISSUE TITLE
Steps required for Windows support?

### ISSUE THREAD

**Issue by fire** [PLSysSec/rlbox_sandboxing_api#25]
Can we track windows support here?

**Comment by shravanrn** [comment]
Sorry for the super delayed response. So the rlbox api itself is already compatible with windows. However the various plugins to rlbox that support different sandboxing mechanisms are not yet compatible. 

Currently the only production ready plugin [rlbox_lucet_sandbox](https://github.com/PLSysSec/rlbox_lucet_sandbox), is not compatible with windows. It is something that will be worked on shortly, but feel free to open a bug there in case you want to track progress via bugs.
