### ISSUE TITLE
Make test optional

### ISSUE THREAD

**Issue by bansan85** [PLSysSec/rlbox_sandboxing_api#28]
This will remove catch2 dependency. This could be done by adding a symbol `-DNO_TEST` for example.

I can do it if you want.

**Comment by shravanrn** [comment]
This is a header only library, so there is nothing really to build here assist from the tests and docs. If you want just the header you can just avoid the build 🙂 Closing this. Reopen if still think there is anything missing

**Comment by bansan85** [comment]
@shravanrn Now that there is a make install to install headers and enable `find_package` feature, what do you think about moving tests and catch2 dependency as an option?

**Comment by shravanrn** [comment]
@bansan85 Yeah, I guess it makes sense. I think the behavior we would want is

1) make build should just output a message saying "nothing to build, run make test or make install"

2) make test should pull in the relevant dependencies, build tests and run the tests.

If you want to set this up, I'd be happy to merge it (don't forgot to update the commands for the CI testing also :) )
